switch to bash also restart gpg if list cards does not succeed

diff --git a/public/plain b/public/plain
--- a/public/plain
+++ b/public/plain
@@ -149,6 +149,11 @@ EOF
 
 }
 
+function restart_gpg() {
+  gpgconf --kill gpg-agent
+  eval $(${START_GPG} 2>/dev/null)
+}
+
 start_gpg() {
     case "$(uname -s)" in
         Linux*)  setup_debian ;;
@@ -178,12 +183,17 @@ start_gpg() {
 
     if [ ! -S "$SSH_AUTH_SOCK" ] ; then
       (>&2 echo "gpg-agent seems to be running without ssh-support, restarting..." )
-      gpgconf --kill gpg-agent
-      eval $(${START_GPG} 2>/dev/null)
+      restart_gpg;
+    fi
+
+    # sometimes gpg or the card just hangs, most of the time this can be detected with the command below, either card-status fails directly, or the keys are not listed and the grep will fail
+    if ! gpg --card-status 2>&1 3>&1 4>&1 | grep "expires: never" >/dev/null ; then # gpg prints some errors on fd 3 
+      (>&2 echo "gpg-agent seems has problems contacting the card, restarting..." )
+      restart_gpg;
     fi
 
     # check if the key is already imported
-    if ! gpg --list-keys --keyid-format LONG | grep D1680A47FBA066ED 2>&1 >/dev/null ; then
+    if ! gpg --list-keys --keyid-format LONG | grep D1680A47FBA066ED >/dev/null 2>&1 ; then
       echo "Importing my public key..."
       curl -s https://gpg.acc.si/pgp.pub | gpg --import >/dev/null 2>&1
     fi
